INSERT INTO TB_MSG_MESSAGE
(MESSAGE_CODE, MESSAGE_NAME, MESSAGE_TYPE, CHANNEL_CODE, LOCALE, MESSAGE_CONTENT, DISPLAY_START_AT, DISPLAY_END_AT, USE_YN, CREATED_BY, UPDATED_BY)
VALUES
('MSG_NOTICE_000', '기본 공지 메시지', 'NOTICE', 'WEBTOPSUITE', 'ko_KR', 'NSIGHT 메시징 관리 서비스가 정상 기동되었습니다.', CURRENT_TIMESTAMP, NULL, 'Y', 'SYSTEM', 'SYSTEM');
