name: Our First Workflow
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello, github actions'
  pwd-ls:
    name: PWD & LS
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run: pwd
      - run: ls -al
      - run: cd bin
      - run: pwd
      - run: ls -l
      
  
  
